dist: trusty


sudo: required
services:
  - docker


script:
  - .travis.d/build.sh

env:
  global:
    - HACKGPROJECT_REV="edd79b515aab77112179e2bf4aacb584c1935c81"

    - DOCKER_ID_USER="hackgt"


branches:
  only:
    - gh-pages
    - /.*/
