dist: trusty


sudo: required
services:
  - docker


script:
  - .travis.d/build.sh

env:
  global:
    - HACKGPROJECT_REV="c42c0b535e813447bcb881a9c3685bf38c797356"

    - DOCKER_ID_USER="hackgt"


branches:
  only:
    - gh-pages
    - /.*/
